version: 2

# Docker environment.
defaults: &defaults
  environment: 
    fork_directory: /go/src/github.com/kubeedge/kubeedge
    original_directory: /fork/src/github.com/kubeedge
  steps:
  - run:
      command: 
        mkdir -p /fork/src/github.com/kubeedge/kubeedge
        cd ${original_directory}
        git clone https://github.com/kubeedge/kubeedge.git
        cd ~
        rsync -az ${original_directory} ${fork_directory}
      
  docker:
  - image: circleci/golang:1.11.1

jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - run: make

  verify:
    <<: *defaults
    steps:
    - checkout
    - run:
        command: make verify

  test:
    <<: *defaults
    steps:
    - checkout
    - run:
        command: make test

  integration:
    <<: *defaults
    steps:
    - checkout
    - run:
        command: make integration_test

workflows:
  version: 2
  workflow:
    jobs:
    - verify
    - build
    - test
    - integration
